from datetime import date


TITULO_PRINCIPAL = 'DATATHON'
TITULO_INTRODUCAO = 'INTRODUÇÃO'
TITULO_HISTORIA = 'EXPLORANDO OS DADOS'
TITULO_ANALISE_EXPLORATORIA = 'METODOLOGIA DE ENSINO E MÉTRICAS'
TITULO_MODELO = 'MODELO DE PREVISÃO'
TITULO_REFERENCIAS = 'REFERÊNCIAS'
DATA_INICIAL = date(2024, 9, 25)